

REQUEST_JOB             = 'REQUEST_JOB'
NEW_JOB                 = 'NEW_JOB'
NO_MORE_JOBS            = 'NO_MORE_JOBS'

REQUEST_EVENT_RANGES    = 'REQUEST_EVENT_RANGES'
NEW_EVENT_RANGES        = 'NEW_EVENT_RANGES'
NO_MORE_EVENT_RANGES    = 'NO_MORE_EVENT_RANGES'

OUTPUT_FILE             = 'OUTPUT_FILE'
