
NEW_PANDA_JOB        = 'JM_NEW_PANDA_JOB'
NO_MORE_WORK         = 'JM_NO_MORE_WORK'
SEND_NEW_PANDA_JOB   = 'JM_SEND_NEW_PANDA_JOB'

SEND_NEW_EVENT_RANGE = 'JC_SEND_NEW_EVENT_RANGE'
OUTPUT_EVENT_FILE    = 'JC_OUTPUT_EVENT_FILE'
NEW_EVENT_RANGE      = 'JC_NEW_EVENT_RANGE'
