

REQUEST_JOB             = 'REQUEST_JOB'
NEW_JOB                 = 'NEW_JOB'
NO_MORE_JOBS            = 'NO_MORE_JOBS'

REQUEST_EVENT_RANGES    = 'REQUEST_EVENT_RANGES'
NEW_EVENT_RANGES        = 'NEW_EVENT_RANGES'
NO_MORE_EVENT_RANGES    = 'NO_MORE_EVENT_RANGES'
REQUEST_PENDING         = 'REQUEST_PENDING'

OUTPUT_FILE             = 'OUTPUT_FILE'

DROID_EXIT              = 'DROID_EXIT'
DROID_HAS_EXITED        = 'DROID_HAS_EXITED'

WALLCLOCK_EXPIRING      = 'WALLCLOCK_EXPIRING'

TYPES=[
   REQUEST_JOB,
   NEW_JOB,
   NO_MORE_JOBS,
   
   REQUEST_EVENT_RANGES,
   NEW_EVENT_RANGES,
   NO_MORE_EVENT_RANGES,
   REQUEST_PENDING,

   OUTPUT_FILE,
   
   DROID_EXIT,
   DROID_HAS_EXITED,

   WALLCLOCK_EXPIRING,
]